wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
    start_time: 1635840266
    t:
      1:
      - 3
      - 5
      3:
      - 16
      4: 3.7.0
      5: 0.12.6
      8:
      - 5
batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 50
filter_size:
  desc: null
  value: 3
learning_rate:
  desc: null
  value: 0.008132
n_filters_factor:
  desc: null
  value: 1.111
